### PR TITLE
Version 0.8.1

### PR DESCRIPTION
**Pull request by botorabi**
- Added localization for German and English to front-end
- Improved UI widgets
- Back-End fixes and improvements

### CODE REVIEW

**Comment by eparo** [comment]
Still some minor UI issues on Report Configuration page (see screen shots):
- element justification
- different row heights
ui-spaces
- empty fields on top of weekday and monthly/weekly choice lists
ui-empty
- width overflows in German language version 
ui-overflow

**Comment by eparo** [comment]
There could be a better (less difficult to understand) reason on wrong time entries than just "406"
ui-406

**Comment by botorabi** [comment]
The last commits on develop branch should fix the issues mentioned above.

**Comment by eparo** [comment]
Fixed a typo and 24h time format. Row heights still not perfect, but this is more of a flutter issue -> close.

**Review by eparo — APPROVED** [review]
OK

**Pull request merged**
